### ISSUE TITLE
Get size returning error

### ISSUE THREAD

**Issue by gclguru** [SoxMax/FG-Size-Changes#4]
The latest Fantasy Grounds update is causing an error with your extension.
[ERROR]  Handler error: [string "scripts/size_change_space.lua"]:17: attempt to call field 'getSize' (a nil value)

**Comment by SoxMax** [comment]
I suspected this might happen. I can hopefully find time by this weekend to get this fixed.

**Comment by SoxMax** [comment]
I think that PR should solve everything, I'll get this up on the forge ASAP
